[package]
name = "tickets"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
log = "0.4"
env_logger = "0.11.3"
num-bigint = "0.4"
octocrab = "0.42.1"
regex = "1.7"
tokio = { version = "1.0", features = ["full"] }