name: "Run FibBot"

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  run-fibbot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 'stable'

      - name: Build the FibBot project
        run: cargo build --release

      - name: Run FibBot
        run: |
          ./target/release/fibbot ${{ github.event.pull_request.number }} ${{ secrets.GITHUB_TOKEN }}
