name: "Run FibBot"

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  run-fibbot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract PR message
        id: pr_message
        run: |
          echo "PR_MESSAGE=$(jq --raw-output .pull_request.body $GITHUB_EVENT_PATH)" >> $GITHUB_ENV

      - name: Check extracted PR message
        run: |
          echo "PR_MESSAGE: ${{ env.PR_MESSAGE }}"

      - name: Run FibBot
        uses: onelrian/fibbot@main
        with:
          entryPoint: "fibbot"
          args: ${{ env.PR_MESSAGE }}  # Pass the PR message here
