name: "Run FibBot"

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  run-fibbot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache FibBot Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.fibbot-cache
          key: fibbot-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            fibbot-${{ runner.os }}-

      - name: Run FibBot
        uses: onelrian/fibbot@main
        with:
          entryPoint: "/usr/local/bin/fibbot"
          args: "${{ github.event.pull_request.number }} ${{ secrets.TOKEN }}"
