name: Compute Fibbonacci on PR content

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  insights:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Rust Action
        uses: ./.github/actions/rust-action
        with:
          pr_number: ${{ github.event.pull_request.number }}