name: "Run FibBot"

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  run-fibbot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build the application
        run: cargo build --release

      - name: Run FibBot
        run: |
          ./target/release/fibbot true 100 ${{ github.event.pull_request.number }} ${{ secrets.GITHUB_TOKEN }}